=== WhyNoobMaster69IsNotAvailable/GG-Bot-Upload-Assistant/schema/site_template_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://json-schema.org/draft-07/schema#",
    "title": "GG-Bot Uploader Site Templates Schema",
    "definitions": {
        "stringArray": {
            "type": "array",
            "items": { "type": "string" },
            "uniqueItems": true,
            "default": []
        },
        "keyValuePair":{
            "type":"object",
            "additionalProperties": false,
            "required": ["key", "value"],
            "properties": {
                "key":{
                    "type":"string",
                    "description": "The key for HTTP header."
                },
                "value":{
                    "type":"string",
                    "description": "The value for HTTP header."
                }
            }
        },
        "technicalJargons":{
            "type":"object",
            "description": "The technical details on how to interact with the trackers upload apis",
            "additionalProperties": false,
            "required": ["authentication_mode", "response_type", "payload_type"],
            "properties": {
                "authentication_mode":{
                    "type":"string",
                    "description": "The authentication method to be used to interact with the upload api",
                    "enum": ["API_KEY", "API_KEY_PAYLOAD", "BEARER", "COOKIE", "HEADER"]
                },
                "response_type":{
                    "type":"string",
                    "description": "The type of response to be expected from the tracker upload api",
                    "enum": ["JSON", "TEXT"]
                },
                "response_action":{
                    "type":"string",
                    "description": "The custom action to be applied to to get the upload status from TEXT based upload response."
                },
                "payload_type":{
                    "type":"string",
                    "description": "Indicates how the payload needs to be sent to tracker upload api",
                    "enum": ["JSON", "MULTI-PART"]
                },
                "request_method":{
                    "type":"string",
                    "description": "The HTTP request method to be used to communicate with api",
                    "enum": ["GET", "POST"],
                    "default": "POST"
                },
                "cookie":{
                    "type":"object",
                    "optional":true,
                    "additionalProperties": false,
                    "properties": {
                        "provider":{
                            "type":"string",
                            "description": "The cookie provider. Tells the uploader on how to get the cookie.",
                            "enum": ["custom_action"]
                        },
                        "data":{
                            "type":"string",
                            "description": "The custom action that needs to be invoked to get cookie for the tracker."
                        }
                    }
                },
                "auth_payload_key":{
                    "type":"string",
                    "description": "The key against which the api key needs to be set in tracker payload"
                },
                "custom_actions":{
                    "$ref": "#/definitions/stringArray"
                },
                "headers":{ "$ref": "#/definitions/authenticationHeaders" }
            },
            "allOf":[
                {
                    "if":{
                        "properties":{ "response_type": { "const": "TEXT" } },
                        "required": [ "response_type" ]
                    },
                    "then":{ "required": ["response_action"] }
                },
                {
                    "if":{
                        "properties":{ "authentication_mode": { "const": "COOKIE" } },
                        "required": [ "authentication_mode" ]
                    },
                    "then":{ "required": ["cookie"] }
                },
                {
                    "if":{
                        "properties":{ "authentication_mode": { "const": "API_KEY_PAYLOAD"} },
                        "required": [ "authentication_mode" ]
                    },
                    "then":{ "required": ["auth_payload_key"] }
                },
                {
                    "if":{
                        "properties":{ "authentication_mode": { "const": "HEADER" } },
                        "required": [ "authentication_mode" ]
                    },
                    "then":{ "required": ["headers"] }
                }
            ]
        },
        "authenticationHeaders":{
            "type": "array",
            "items": { "$ref": "#/definitions/keyValuePair" }
        }
    },
    "required": [
        "name", "url", "upload_form", "torrents_search",
        "source", "platform", "bbcode_line_break", "title_separator",
        "torrent_title_format", "dupes", "Default", "Optional",
        "Required", "translation", "hybrid_mappings"
    ],
    "type": ["object"],
    "additionalProperties": true,
    "properties": {
        "name":{
            "type":"string",
            "description": "The full name of the tracker"
        },
        "url":{
            "type":"string",
            "format": "uri",
            "description": "The url of the tracker"
        },
        "upload_form":{
            "type":"string",
            "format": "uri",
            "description": "The url to which GG-BOT should send the upload payload"
        },
        "torrents_search":{
            "type":"string",
            "format": "uri",
            "description": "The url from which GG-BOT can fetch torrents already on tracker to check for dupe before uploading"
        },
        "source":{
            "type":"string",
            "description": "The value for `source` tag in torrent metadata"
        },
        "platform":{
            "type":"string",
            "description": "The platform / codebase on which the tracker is built."
        },
        "bbcode_line_break":{
            "type":"string",
            "description": "The character that the tracker's bbcode engine uses for line breaks. [\\n, <br>]"
        },
        "title_separator":{
            "type":"string",
            "description": "The separator to be used while formatting torrent title for tracker. Eg: .(dot), (space), etc... "
        },
        "description_components":{
            "type":"object",
            "description": "The wrappers for various bbcode / html tags. Note that the starting and ending tags should be separated by a space.",
            "additionalProperties": false,
            "properties": {
                "spoiler_code": {
                    "type":"string",
                    "description": "The bbcode / html wrapper to be used for creating 'Spoilers'."
                },
                "notes_code": {
                    "type":"string",
                    "description": "The bbcode / html wrapper to be used for creating 'Notes'."
                },
                "quote_code": {
                    "type":"string",
                    "description": "The bbcode / html wrapper to be used for creating 'Quotes'."
                },
                "alert_code": {
                    "type":"string",
                    "description": "The bbcode / html wrapper to be used for creating 'Alerts'."
                },
                "code_code": {
                    "type":"string",
                    "description": "The bbcode / html wrapper to be used for creating 'Codes'."
                }
            }
        },
        "technical_jargons": { "$ref": "#/definitions/technicalJargons" },
        "hybrid_mappings":{
            "type":"object",
            "default":{}
        },
        "translation":{
            "type":"object"
        },
        "Required":{
            "type":"object"
        },
        "Optional":{
            "type":"object",
            "default":{}
        },
        "Default":{
            "type":"object",
            "default":{}
        },
        "dupes":{
            "type":"object",
            "properties": {
                "technical_jargons": { "$ref": "#/definitions/technicalJargons" },
                "url_format": {
                    "type": "string",
                    "description": "The URL formatting to be applied to create the search url"
                },
                "strip_text":{
                    "type": "boolean",
                    "description": "Indicates whether the tt in imdb needs to be removed or not",
                    "default" : false
                },
                "parse_json":{
                    "type":"object",
                    "description": "Tells the uploader on how to parse the dupe check response from tracker",
                    "required": ["is_needed"],
                    "properties": {
                        "is_needed":{
                            "type":"boolean",
                            "default":false,
                            "description": "Indicates whether the uploader needs to apply any parsing to the dupe check response from tracker"
                        },
                        "top_lvl":{
                            "type":"string",
                            "description": "Mentions the first attribute in the response json which contains the list of object. (each object is a torrent in the tracker)"
                        },
                        "second_level":{
                            "type":"string",
                            "description": "If top_lvl item is an object, and the torrent items is present in a key in this object, it can be fetched by this attribute."
                        },
                        "torrent_details":{
                            "type":"string",
                            "description": "If the top_lvl item is an array, and the torrent object is under another attribute in this object, then it can be fetched by this attribute."
                        },
                        "torrent_name":{
                            "type":"string",
                            "description": "The attribute in the torrent object which contains the name of the torrent.",
                            "default": "name"
                        },
                        "combine_fields":{
                            "type":"boolean",
                            "description": "Indicates whether the uploader needs to concatenate multiple attribute to create the torrent tile."
                        },
                        "fields": { "$ref": "#/definitions/stringArray" }
                    },
                    "allOf": [
                        {
                            "if":{
                                "required": ["is_needed"],
                                "properties": {
                                    "is_needed":{ "const": true }
                                }
                            },
                            "then":{
                                "required": ["top_lvl"]
                            }
                        },
                        {
                            "if":{
                                "required": ["combine_fields"],
                                "properties": {
                                    "combine_fields":{ "const": true }
                                }
                            },
                            "then":{
                                "required": ["fields"]
                            }
                        }
                    ]
                },
                "payload":{
                    "type":"string",
                    "description": "If the technical_jargons.request_method is POST, then the payload to be send needs to be provided here. This must be a valid json string. Contents to be replaced must be enclosed with <>"
                }
            },
            "allOf": [
                {
                    "if":{
                        "properties": {
                            "technical_jargons":{
                                "properties": {
                                    "request_method":{
                                        "const": "POST"
                                    }
                                }
                            }
                        }
                    },
                    "then":{
                        "required": ["payload"]
                    }
                }
            ]
        },
        "torrent_title_format":{
            "type":"object",
            "additionalProperties": false,
            "properties":{
                "movie":{
                    "type":"object"
                },
                "episode":{
                    "type":"object"
                }
            }
        },
        "banned_groups": { "$ref": "#/definitions/stringArray" }
    }
}

=== WhyNoobMaster69IsNotAvailable/GG-Bot-Upload-Assistant/site_templates/torrentleech.json
{
    "name": "TorrentLeech",
    "url": "https://www.torrentleech.org/",
    "upload_form": "https://www.torrentleech.org/torrents/upload/apiupload",
    "torrents_search": "https://www.torrentleech.org/torrents/upload/apiupload",
    "source": "TorrentLeech.org",
    "platform": "TorrentLeech",
    "bbcode_line_break": "\n",
    "title_separator" : " ",

    "description_components":{
        "code_code": "[code][/code]",
        "quote_code":"[quote][/quote]"
    },

    "technical_jargons": {
        "authentication_mode": "API_KEY",
        "response_type": "TEXT",
        "response_action": "modules.custom_actions.tl_actions.check_successful_upload",
        "payload_type": "MULTI-PART",
        "custom_actions": [
            "modules.custom_actions.tl_actions.add_announce_pid_to_payload",
            "modules.custom_actions.tl_actions.rewrite_description"
        ]
    },

    "hybrid_mappings": {
        "category": {
            "required": true,
            "prerequisite": [
                "resolution", "category_id", "type_id"
            ],
            "mapping":{
                "36":{
                    "_comment": "Movies|Foregin",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["1"]
                    },
                    "$.tmdb_metadata.original_language":{
                        "data_source": "torrent",
                        "not": true,
                        "values": ["en"]
                    }
                },
                "47":{
                    "_comment": "Movies|4K",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["1"]
                    },
                    "resolution":{
                        "data_source": "tracker",
                        "values": ["2160p"]
                    }
                },
                "12":{
                    "_comment": "Movies|DVD",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["1"]
                    },
                    "type_id":{
                        "data_source": "tracker",
                        "values": ["7"]
                    }
                },
                "13":{
                    "_comment": "Movies|BluRay",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["1"]
                    },
                    "type_id":{
                        "data_source": "tracker",
                        "values": ["1", "2"]
                    }
                },
                "14":{
                    "_comment": "Movies|BluRayRip",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["1"]
                    },
                    "type_id":{
                        "data_source": "tracker",
                        "values": ["3"]
                    }
                },
                "37":{
                    "_comment": "Movies|WEBRip",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["1"]
                    },
                    "type_id":{
                        "data_source": "tracker",
                        "values": ["4", "5"]
                    }
                },
                "43":{
                    "_comment": "Movies|HDRip",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["1"]
                    },
                    "type_id":{
                        "data_source": "tracker",
                        "values": ["6"]
                    }
                },
                "44":{
                    "_comment": "TV|Foregin",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["2"]
                    },
                    "$.tmdb_metadata.original_language":{
                        "data_source": "torrent",
                        "not": true,
                        "values": ["en"]
                    }
                },
                "27":{
                    "_comment": "TV|BoxSets",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["2"]
                    },
                    "episode_number": {
                        "data_source": "torrent",
                        "values": [
                            "0"
                        ]
                    }
                },
                "26":{
                    "_comment": "TV|Episodes",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["2"]
                    },
                    "resolution_id": {
                        "data_source": "tracker",
                        "values": [
                            "576p",
                            "480p",
                            "Other"
                        ]
                    }
                },
                "32":{
                    "_comment": "TV|EpisodesHD",
                    "category_id":{
                        "data_source": "tracker",
                        "values": ["2"]
                    }
                }
            }
        }
    },

    "translation": {
        "dot_torrent": "torrent",
        "description": "description",
        "imdb_with_tt":"imdb",
        "hybrid_type_1": "category",
        "torrent_title": "name",
        "mediainfo": "mediainfo",
        "bdinfo": "bdinfo",
        "type": "category_id",
        "source": "type_id",
        "resolution": "resolution",
        "nfo_file": "nfo"
    },

    "Required": {
        "torrent": "file",
        "description": "string",
        "category": "hybrid_type",
        "name": "string",
        "imdb":"string",
        "category_id": {
            "1": "movie",
            "2": "episode"
        },

        "type_id": {
            "1": {
                "disc": 1,
                "bluray_disc": 2,
                "dvd_disc": 2
            },
            "2": {
                "remux": 1,
                "bluray_remux": 2,
                "dvd_remux": 2
            },
            "3": {
                "bluray_encode": 1
            },
            "4": {
                "webdl": 2,
                "web_dl": 2
            },
            "5": {
                "webrip": 2,
                "web_rip": 2
            },
            "6": {
                "hdtv": 1
            },
            "7":{
                "dvd": 1
            }
        },

        "resolution": {
            "2160p": {
                "2160p": 1
            },
            "1080p": {
                "1080p": 1
            },
            "1080i": {
                "1080i": 1
            },
            "720p": {
                "720p": 1
            },
            "576p": {
                "576p": 2,
                "576i": 2
            },
            "480p": {
                "480p": 2,
                "480i": 2
            },
            "Other": {
                "other": 2,
                "4360p": 2
            }
        }
    },

    "Optional": {
        "nfo": "file",
        "bdinfo": "string",
        "mediainfo": "string"
    },

    "Default":{
        "announcekey": ""
    },

    "dupes": {
        "skip_dupe_check": true,
        "technical_jargons": {
            "authentication_mode": "HEADER",
            "headers" : [
                {
                    "key": "ApiUser",
                    "value": "API_USER"
                },
                {
                    "key": "ApiKey",
                    "value": "API_KEY"
                }
            ],
            "payload_type": "MULTI-PART",
            "request_method": "GET",
            "response_type": "JSON"
        },

        "url_format": "{search_url}{imdb}",
        "strip_text": false,

        "parse_json": {
            "is_needed": true,
            "top_lvl": "torrentList",
            "torrent_name": "name"
        }
    },

    "torrent_title_format": {
        "episode": {
            "bluray_disc": "{title} {year} {s00e00} {screen_size} {region} {source} {dv} {hdr} {video_codec} {audio_codec} {audio_channels} {atmos} {release_group}",
            "bluray_remux": "{title} {year} {s00e00} {repack} {screen_size} {uhd} {hybrid} {source} {remux} {dv} {hdr} {video_codec} {audio_codec} {audio_channels} {atmos} {release_group}",
            "bluray_encode": "{title} {year} {s00e00} {repack} {screen_size} {uhd} {hybrid} {source} {audio_codec} {audio_channels} {atmos} {dv} {hdr} {video_codec} {release_group}",
            "web": "{title} {year} {s00e00} {repack} {screen_size} {web_source} {web_type} {audio_codec} {audio_channels} {atmos} {dv} {hdr} {video_codec} {release_group}",
            "hdtv": "{title} {year} {s00e00} {repack} {screen_size} {hybrid} {source} {audio_codec} {audio_channels} {video_codec} {release_group}",
            "dvd": "{title} {year} {s00e00} {edition} {repack} {screen_size} {region} {hybrid} {source} {video_codec} {remux} {audio_codec} {audio_channels} {atmos} {release_group}"
        },

        "movie": {
            "bluray_disc": "{title} {year} {edition} {repack} {screen_size} {region} {source} {dv} {hdr} {video_codec} {audio_codec} {audio_channels} {atmos} {release_group}",
            "bluray_remux": "{title} {year} {edition} {repack} {screen_size} {uhd} {hybrid} {source} {remux} {dv} {hdr} {video_codec} {audio_codec} {audio_channels} {atmos} {release_group}",
            "bluray_encode": "{title} {year} {edition} {repack} {screen_size} {uhd} {hybrid} {source} {audio_codec} {audio_channels} {atmos} {dv} {hdr} {video_codec} {release_group}",
